---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: prow
  name: plugins
data:
  plugins.yaml: |
    plugins:
      kong-ci-bot/prow-test:
        plugins:
        - approve
        - assign
        - blunderbuss
        - cat
        - cla
        - dog
        - golint
        - goose
        - heart
        - help
        - hold
        - invalidcommitmsg
        - label
        - lgtm
        - lifecycle
        - milestoneapplier
        - owners-label
        - pony
        - retitle
        - shrug
        - sigmention
        - size
        - skip
        - slackevents
        - transfer-issue
        - trick-or-treat
        - trigger
        - verify-owners
        - welcome
        - wip
        - yuks
